### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Kricket** [wisdom-framework/wisdom-jcr#10]
We have a fairly simple wisdom project. We are in the course of converting the persistence layer from something simple (commons-configuration) to JCR.

It was quite a challenge to get wisdom-jcr functioning. Part of it is because we don't really know much about all the pieces involved, but another is that there are a few tricks that must be used to get it working.

It might make adoption easier if the documentation included a few lines about the following:
- a quick overview of the different components (Jcrom, modeshape, infinispan) and how they are put together by wisdom-jcr
- a more detailed explanation of what configuration needs to be put in application.conf: where does all this stuff come from? what does it mean? what's possible? --> a reference to the source would be helpful
- links to documentation for the other config files (repository JSON spec, CND file format)
- a note about the hack needed for wisdom to find the CND file for dev repositories
- a note about what libs may need to be added to wisdom's configuration in the POM in order for OSGi to work

**Comment by amischler** [comment]
Added https://github.com/wisdom-framework/wisdom-jcr/issues/12 regarding the hack needed for CND file

**Comment by amischler** [comment]
Thanks for your feedback on wisdom-jcr. I have updated the documentation, I hope this will help newcomers. 

Feel free to reopen this issue if some points are still not clear.
