### ISSUE TITLE
As a developer I would like to provide my own implementation of Jcrom

### ISSUE THREAD

**Issue by agonist** [wisdom-framework/wisdom-jcr#11]
In the module wisdom-jcr-core in [JcrRepository](https://github.com/wisdom-framework/wisdom-jcr/blob/master/wisdom-jcr-core/src/main/java/org/wisdom/jcrom/runtime/JcrRepository.java), we instanciate Jcrom by doing : 

`this.jcrom = new Jcrom(jcromConfiguration.isCleanNames(), jcromConfiguration.isDynamicInstantiation());`

But I would like to let the developer provide his own implementation of Jcrom. What is the best approche to achieve this ?

We want to have a default implementation like the actual and be able to override this default implementaion.

Is there a way to do that with IPojo ?
Something like injecting Jcrom with : 

``` java
 @Requires
 Jcrom jcrom;
```

By default return the default implementation and if another wisdom module provide an implementation it will use this one.

@cescoffier any suggestions ?

**Comment by cescoffier** [comment]
Something like that:

```
@Requires(defaultImplementation=YourDefaultJcromImplementation.class)
Jcrom jcrom
```

If there is no JCrom service, it creates a new instance of the given class (calling an empty constructor). 

Another possibility if to set a `service.ranking`. A service with a higher `service.ranking` will be preferred to a service without or with a lower one. The `service.ranking` is a service property with an integer value.

In this approach you create you own Jcrom service and set a very low `service.ranking` (0). a developper willing to customize the jcrom service expose the same service but with a `service.ranking` > 0.

**Comment by agonist** [comment]
Easy ! Thanks

**Comment by agonist** [comment]
If JcromProvider is my service interface, is this correct if my DefaultJcrom look like this : 

``` java
public class DefaultJcrom implements JcromProvider {

    @Requires
    ApplicationConfiguration applicationConfiguration;

    private JcromConfiguration jcromConfiguration;

    private Jcrom jcrom;

    public DefaultJcrom() {
        jcromConfiguration = JcromConfiguration.fromApplicationConfiguration(applicationConfiguration);
        jcrom = new Jcrom(jcromConfiguration.isCleanNames(), jcromConfiguration.isDynamicInstantiation());
    }

    @Override
    public Jcrom getJcrom() {
        return jcrom;
    }
}
```

and inject it : 

``` java
    @Requires(optional = true, defaultimplementation = DefaultJcrom.class)
    JcromProvider jcromProvider;
```

Or I'm not able to do @Require in this class ?

update : it seem there is an error with this code :  

```
←[1;31m[ERROR]   o.o.u.l.i.o.LoggerService←[0;39m ←[36m{[iPOJO] pool-1-thread-1}←[0;39m - [ERROR]  : Cannot load the default-implementation (unexpected exception) org.wisdom.jcrom.runtime.DefaultJcrom
←[1;31m[ERROR]   o.o.u.l.i.o.LoggerService←[0;39m ←[36m{[iPOJO] pool-1-thread-1}←[0;39m - [ERROR] org.wisdom.jcrom.runtime.JcrRepository : Cannot load the default-implementation (unexpected exception) org.wisdom.jcrom.runtime.DefaultJcrom
```

**Comment by cescoffier** [comment]
That's exactly what you have to do.
If there is no available JcromProvider is will use your default one, else
it will use the available one.

2015-05-07 10:48 GMT+02:00 Bastien notifications@github.com:

**Comment by agonist** [comment]
Fixed with https://github.com/wisdom-framework/wisdom-jcr/commit/b7cd7518853a2abb06ab1b610bc66114b09b492d

**Comment by agonist** [comment]
I have an issue with this, when I try to provide an implementation to override the default one, it doesn't work and still use the default one.

The service I try to provide : 

``` (java)
@Component
@Instantiate
@Provides(specifications = {JcromProvider.class})
public class CloudJcromProvider implements JcromProvider {

    private MixinJcrom jcrom;

    @Requires
    private JcrRepository repository;

    @Override
    public Jcrom getJcrom(JcromConfiguration jcromConfiguration) {
        if (jcrom == null) {
            jcrom = new MixinJcrom(jcromConfiguration.isCleanNames(), jcromConfiguration.isDynamicInstantiation(), repository.getSession());
        }
        return jcrom;
    }
}
```

Is this correct ? @cescoffier

**Comment by cescoffier** [comment]
Is your implementation available when the default one is picked ?

2015-05-12 11:36 GMT+02:00 Bastien notifications@github.com:

**Comment by agonist** [comment]
Yes it appear in the service list

org.wisdom.jcrom.service.JcromProvider
factory.name = com.dooapp.jcrom.CloudJcromProvider
instance.name = com.dooapp.jcrom.CloudJcromProvider-0
objectClass = [org.wisdom.jcrom.service.JcromProvider]
service.bundleid = 54
service.id = 634
service.scope = bundle

**Comment by cescoffier** [comment]
Is it fixed ?

2015-05-12 16:51 GMT+02:00 Bastien notifications@github.com:

**Comment by agonist** [comment]
Yes it was a fail from me. My Service was not in the package service so not exported..... other modules was not able to find it
