### ISSUE TITLE
JCROM mapper classes are not unloaded when bundle is unloaded

### ISSUE THREAD

**Issue by Riduidel** [wisdom-framework/wisdom-jcr#16]
According to one discussion in mailing-list

> Concerning this reference hunt, I also suspect widom-jcr (and more specifically jcrom or modeshape) to have some kind of object cache where my classes are stored. Because on application reload, I always get those ClassCastException in code involving persistence layer. So, I would be tempted to say that some cleanup code is missing in wisdom-jcr.
> 
> To my mind, it may be a cool idea to add some invalidation code into the wisdom-jcr JcrRepository stop() method, that would try to cleanup the various jcrom objects (typically, jcrom seems to maintain a map containing mapped classes, that is not released when bundle is stopped - partly because jcrom is not OSGi compatible, and partly because jcrom is absolutely not designed in a way that would allow such things).

Which lead to 

> Actually, there is already some cleanup code in wisdom-jcr : the JcromCrudProvider unregisters the crud services registered for a removed bundle (see JcromCrudProvider#removedBundle).
> 
> It don't think that ModeShape maintains references to some classes, since the JCR repository has no idea of the model classes, it is just manipulating nodes and properties.
> 
> But you are right, JCROM certainly keeps references to the mapped classes (see Mapper.mappedClasses) and there is no way currently to "unmap" classes in JCROM. Some modifications might be required in JCROM to support this. It don't see a workaround for this for the moment, maybe you have an idea?

**Comment by Riduidel** [comment]
Clément answered the annoying question of "how to test" :

> You can do that using an in-container test (extends WisdomTest). You retrieve the bundle context using the @Inject annotation, and then do something like:

```
Bundle b = context.installBundle(url);
b.start();
b.uninstall();

b = context.installBundle(url);
b.start();
b.uninstall();

// Check that everything is fine
```

> url is the url of the bundle you want to deploy. To build a bundle ‘dynamically’, you can have a look to tiny bundle (https://github.com/wisdom-framework/wisdom/blob/master/framework/i18n-service/src/test/java/org/wisdom/i18n/InternationalizationServiceSingletonIT.java)

**Comment by amischler** [comment]
Currently it's not possible to remove mapped classes from JCROM. An issue has been opened to request unmap methods on JCROM : https://github.com/Kobee1203/jcrom/issues/113

**Comment by Riduidel** [comment]
Is it time to remind you violence is always a solution ? :-D

**Comment by amischler** [comment]
Actually, this is not as easy as expected since JCROM also automatically map classes referenced by a mapped class.

Determining how to handle these referenced classes is not trivial when removing a bundle.

I'm thinking a another approach which would consist of creating a single persistence unit with a single Jcrom instance for each loaded bundle containing mapped entities. This would allow to throw the whole persistence unit attached to a bundle when unloading this bundle. In this case this would not be necessary to "unmap" classes from the Jcrom object.

What do you think of this approach? Do you see cases where this could create problems to have independent persistent units per bundle?

**Comment by Riduidel** [comment]
Le 24/06/2015 17:04, Antoine Mischler a écrit :

> I'm thinking a another approach which would consist of creating a 
> single persistence unit with a single Jcrom instance for each loaded 
> bundle containing mapped entities. This would allow to throw the whole 
> persistence unit attached to a bundle when unloading this bundle. In 
> this case this would not be necessary to "unmap" classes from the 
> Jcrom object.
> 
> What do you think of this approach? Do you see cases where this could 
> create problems to have independent persistent units per bundle?

Why could it be a problem ? i suggest you try this solution, and 
execution should fast trigger some interesting feedbacks :-)

**Comment by Riduidel** [comment]
OK, so, if I understand correctly, the workaround would involve
1. Rewrite the JcromCrudProvider to return, in the `addingBundle` method, a new object that will contain the `Jcrom` instance and the map associating `Crud` (well, `JcrCrudService` if i understand correctly) used to map classes in that bundle using `Jcrom` object given with the ServiceRegistration infos. The `removingBundle` method would then be changed to get that object, perform the unregistration, and leave. Notice I would also have to add a call to `JcromProvider` to create the instances
2. rewrite the `JcrRepository` to remove the `Jcrom` reference there and replace it with the newly created object.

Am I right ?

**Comment by amischler** [comment]
That sounds good.

**Comment by Riduidel** [comment]
Strangely, when doing so, the JcromCrudProvider addingBundle and 
removedBundle are never called. Is there something that should be 
changed when the type parameter of JcromCrudProvider get changed ?
I will push all the modified code into a new branch, to have it 
available to you.

**Comment by Riduidel** [comment]
Continuing my investigations ... because the bug was not that easy :-)

It appear that, when the bug happens, the jcrom `Mapper#mappedClasses` contains classes which classloader is not the same than the one of the class given as parameter to `Mapper#getClassForName`, which is specially weird, because I was thinking all the classes would come from the same classloader.

I will investigate more on that point ....

OK ... 

![it came from the moon](http://b.decitre.di-static.com/media/catalog/product/cache/1/image/200x303/9df78eab33525d08d6e5fb8d27136e95/9/7/8/2/9/1/6/7/9782916739298FS.gif)

Well, in fact, from `org.jcrom.util.ReflectionUtils#getParameterizedClass`, which in fact read the class object from the field declared type ... A field which is read by `org.jcrom.util.ReflectionUtils#getDeclaredAndInheritedFields`, which in turn uses the object type given by `org.jcrom.Mapper#mapNodeToClass`, which in fact means that the whole stuff come from the `obj` class, which may not be loaded by the right class loader ... and it appears that obj class is in fact the `org.jcrom.dao.AbstractJcrDAO` entity class !
