### ISSUE TITLE
Java 1.8 bytecode

### ISSUE THREAD

**Issue by cescoffier** [wisdom-framework/wisdom-jcr#3]
Hi,

The module is requesting Java 8. I'm not against it, but it need to be clear (because, the rest of Wisdom requires Java 1.7).

**Comment by amischler** [comment]
Java 8 is not absolutely required, I have updated the maven.compiler.target option to produce 1.7 bytecode. 

Is it OK if I leave the maven.compiler.source on 1.8?

**Comment by cescoffier** [comment]
I don't really know the impact of keeping the source level to 1.8. I may be
weird on stuff like lambdas.

2015-03-25 10:05 GMT+01:00 Antoine Mischler notifications@github.com:

**Comment by amischler** [comment]
Right, I have also set the maven.compiler.source to 1.7
