### ISSUE TITLE
Memory leak - Session should be a short lived object

### ISSUE THREAD

**Issue by amischler** [wisdom-framework/wisdom-jcr#46]
The current implementation uses a single Jcr Session which is never closed during application runtime.

This is not recommended by Modeshape and it is causing memory leaks for long running application. See https://developer.jboss.org/thread/260630

A Session should be opened for each request or task accessing the Jcr repository.

**Comment by cescoffier** [comment]
Thanks for the PR, I just merged it.

**Comment by amischler** [comment]
Thank you @cescoffier !

By the way : I managed to open/close the JcrSession automatically in the context of a request (using the CloseJcrSessionFilter and SessionExecutionContextService for @Async requests)

But I was not able to automatically do that for accesses to the Jcr Repository made out of the context of a request, for example in the context of a task executed in the ManagedScheduledExecutorService or in the @Validate method of the component). For those cases some modifications are required in the consumer code to use a try with resource to manually open the session. (see here for an example https://github.com/wisdom-framework/wisdom-jcr/blob/master/modeshape-sample/src/main/java/todo/controllers/TodoController.java#L64) 

Any idea how this could be improved ?
