### ISSUE TITLE
Include wisdom-jcr in maven central

### ISSUE THREAD

**Issue by Kricket** [wisdom-framework/wisdom-jcr#8]
The artifacts for wisdom-jcr are not present in maven central.

Please either deploy to maven central, or update readme to indicate at what public repository the artifacts are available.

**Comment by cescoffier** [comment]
It's because there is no release yet. Snapshots are available from the oss-snapshot repository: https://oss.sonatype.org/content/repositories/snapshots/org/wisdom-framework/jcr/

Snapshots are deployed automatically.

**Comment by amischler** [comment]
I started the release process for the 0.1.0 version.
I do not have the rights to deploy to org/wisdom-framework/jcr on sonatype.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.1:deploy (default-deploy) on project wisdom-jcr: Failed to deploy artifacts: Could not transfer artifact org.wisdom-framework.jcr:wisdom-jcr:pom:0.1.0 from/to sonatype-nexus-staging (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Access denied to: https://oss.sonatype.org/service/local/staging/deploy/maven2/org/wisdom-framework/jcr/wisdom-jcr/0.1.0/wisdom-jcr-0.1.0.pom, ReasonPhrase: Forbidden.
```

@cescoffier : do you want me to ask for access rights here https://issues.sonatype.org/browse/OSSRH-7974? (my account is https://issues.sonatype.org/secure/ViewProfile.jspa?name=antoine)
Or do you prefer to deploy it yourself? (tag wisdom-jcr-0.1.0)
Thanks.

**Comment by cescoffier** [comment]
I've asked Joel. 
(https://issues.sonatype.org/browse/OSSRH-7974)

**Comment by amischler** [comment]
Ok, thanks.

**Comment by cescoffier** [comment]
Permissions granted, you should be able to deploy your artifacts.

**Comment by amischler** [comment]
Thanks, artifacts deployed.
